### ISSUE TITLE
Unexpected `Pre-release declarations` compilation errors when included as a dependency

### ISSUE THREAD

**Issue by Wesley-Young** [karmakrafts/Kompress#3]
The published library (version 1.4.1) is compiled with some pre-release features, and this caused compiliation error in the project without such features enabled.

```
Package 'dev.karmakrafts.kompress' was compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler. Enabled pre-release features: ExplicitBackingFields
```

ref: https://github.com/LagrangeDev/acidify/actions/runs/24392949520/job/71243479469

**Comment by KitsuneAlex** [comment]
Hm yes, this is indeed an issue. I am already actively using context parameters, local type aliases and explicit backing fields. For this library however, it shouldn't be a problem to factor those features out if there is demand :)
Will include this change in 1.4.2 when i update to 2.3.21.

**Comment by KitsuneAlex** [comment]
Fixed with latest release
